### ISSUE TITLE
create mirror repos origanized by original repo name

### ISSUE THREAD

**Issue by redguardtoo** [redguardtoo/elpa-mirror#13]
as title, since elpa.gnu.org crash always.

**Comment by walthinking** [comment]
I can't create mirror repos and the prompt message  is "文件名、目录名或卷标语法不正确" while my output path is either "c:\emacs" or "E:/emacs/". Thinks for your Emacs configuration.

**Comment by redguardtoo** [comment]
because you are the first person to use elpa-mirror under windows. I suppose you already installed the cygwin whose tar&cp accessible.

I will try to figure out a solution.
