### ISSUE TITLE
[question] works for melpa? 

### ISSUE THREAD

**Issue by ninrod** [redguardtoo/elpa-mirror#14]
Hi @redguardtoo and thanks for this. 

I'm looking for a way to download the whole MELPA repo to a local folder. Is there a way to do this with your solution?

thanks in advance.

**Comment by redguardtoo** [comment]
Melpa has some rsync service

My way is simpler and more practical though.

Only packages actually used is included in local repo. So repo size is much smaller. You control exact version of every package.

**Comment by ninrod** [comment]
Ok. Please see if I understood correctly. I want to use your solution for my current spacemacs configuration through melpa. For that I have to:

(premise: I have access to github.com clones behind corp firewall)

0. put your `elpa-mirror.el` in a loadpath function somewhere in my `~/.spacemacs/init.el` 
0. issue `M-x elpamr-create-mirror-for-installed`, 
0. the packages will be in a `~/myelpa` folder
0. I create a git repo with that folder, push that to github
0. in my workplace, I clone the github repo to `~/myelpa` on my work machine behind corp firewall
0. change my `~/.spacemacs/init.el` to search for packages inside the `~/myelpa` cloned repo.

0. profit.

Is that the hang of it? 

thanks in advance

**Comment by redguardtoo** [comment]
Yes
