### ISSUE TITLE
Create a mirror-tarball instead of directory

### ISSUE THREAD

**Issue by tumashu** [redguardtoo/elpa-mirror#16]
is it possible create a elpa-mirror-tarball directly?  for its size is much smaller and suit for add to my config git repos

**Comment by redguardtoo** [comment]
what do you mean?

**Comment by tumashu** [comment]
create a elpa-mirror.tar.gz instead of elpa-mirror directory

**Comment by tumashu** [comment]
git can auto compress its file, so this feature is not needed, i think :-)
