### ISSUE TITLE
Error when creating mirror

### ISSUE THREAD

**Issue by theoreticMK** [redguardtoo/elpa-mirror#20]
After updating emacs to version 26.0.90, I got an error when calling elpamr-create-mirror-for-installed

It fails on the first installed package (anzu) with a long backtrace and the final error message:

> condition-case: Wrong type argument: sequencep, #s(package-desc anzu (20161017 907) "Show number of matches in mode-line while searching" ((emacs (24 3))) single "melpa" nil ((:commit . "e6c56ca8b23ac433f7be58b6f3f50801dd4164e4") (:url . "https://github.com/syohex/emacs-anzu")) nil)

**Comment by redguardtoo** [comment]
Emacs v26 possibly changed its API. I'll look into it.

**Comment by theoreticMK** [comment]
Issue is solved with the latest update of elpa-mirror
