### ISSUE TITLE
not working for doom-emacs develop branch

### ISSUE THREAD

**Issue by showgood** [redguardtoo/elpa-mirror#23]
used to work great for doom-emacs master branch, but since I switch to use the develop branch of doom emacs (https://github.com/hlissner/doom-emacs), this package stops working.

It's as if it couldn't detect any package installed, so nothing happens after running command `elpamr-create-mirror-for-installed`.

my environment:
`GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F2511)) of 2018-05-30`

`macOS Mojave 10.14.2 (18C54)`

**Comment by redguardtoo** [comment]
show me the directory layout of your `.emacs.d`

This package just tar the content of `~/.emacs.d/elpa`.

**Comment by showgood** [comment]
doom emacs (develop) branch puts packages at these locations:
`~/.emacs.d/.local/packages/elpa`
`~/.emacs.d/.local/packages/quelpa`

**Comment by redguardtoo** [comment]
I see. There is easy workaround. Let me try `doom-emacs`

**Comment by redguardtoo** [comment]
Can't reproduce the issue with `develop` branch. What's output of `mkdir -p ~/myelpa && emacs --batch -l ~/.emacs.d/init.el -l ~/projs/elpa-mirror/elpa-mirror.el --eval='(progn (setq elpamr-debug t) (setq elpamr-default-output-directory "~/myelpa"))' --eval='(elpamr-create-mirror-for-installed)'`?

Can you check `myelpa` directory and find what package is missing?

**Comment by showgood** [comment]
by running the command you provided on console works, but it doesn't work if I do `M-x elpamr-create-mirror-for-installed` within Emacs, it produces nothing in the `~/myelpa~ directory.

**Comment by redguardtoo** [comment]
That's strange. `M-x eval-expression` and input `(setq elpamr-debug t)`, run elpa-mirror again. What's the output in *Message* buffer?

**Comment by showgood** [comment]
there is output from elpamr package in the Message buffer after I followed the steps you mentioned.

I think the issue is elpamr didn't detect any packages for some reason

**Comment by redguardtoo** [comment]
I need see the full message. The cli I asked you to run is exactly the same command you run inside Emacs.

Could you test a fresh installed doom?

**Comment by showgood** [comment]
I did test from a fresh installed doom, after following the steps, there is NO output in message buffer..

**Comment by redguardtoo** [comment]
What's the value of `package-user-dir` and `package-alist`?

**Comment by showgood** [comment]
`package-user-dir` has value: `/Users/showgood/.emacs.d/.local/packages/elpa`
`package-alist` has value `nil`

**Comment by redguardtoo** [comment]
Thanks a lot. That should be enough to debug.

**Comment by redguardtoo** [comment]
Tested `doom-emacs` ab616cfb (HEAD -> develop, origin/develop) 2019-03-26 Merge pull request #1247 from jdnavarro/develop. Everything works.
`package-alist` is not `nil`. Emacs 26.1 on Linux.

**Comment by showgood** [comment]
hmm, interesting.. I tried on few machines, always not working.
anyone, I can use command line, thanks for the debugging!

**Comment by redguardtoo** [comment]
Maybe you can send a bug report to doom-emacs devleoper? As I can see, looks he did change the default `package.el` behavior for some reason. So `package-alist` is nil in certain scenario.

**Comment by showgood** [comment]
thanks for the help and triaging!
