### ISSUE TITLE
PAXHeader cause the package installation failed

### ISSUE THREAD

**Issue by baolonglin** [redguardtoo/elpa-mirror#26]
The tar which I used is:
tar (GNU tar) 1.27.1

It use the --format=posix(pax) by default, it will cause error:
"Package does not untar cleanly into directory %s/"

Patch like blow solve the error:
```lisp
          (setq tar-cmd (concat (if (elpamr--is-mac) "COPYFILE_DISABLE=\"\" " "")
                                (elpamr--executable-find "tar")
                                " cf "
                                (elpamr--fullpath output-directory dir)
                                ".tar --exclude=\"*.elc\" --exclude=\"*~\" "
+                                " --format=gnu "
                                " -C "
                                package-user-dir
                                " "
                                dir))
```

**Comment by redguardtoo** [comment]
Could you give me more details? What's your OS? What's output of `tar --version`?

**Comment by baolonglin** [comment]
OS: 
NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp2"

Tar version:
tar (GNU tar) 1.27.1
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

**Comment by redguardtoo** [comment]
c9d4f69 gnu tar format could be screwed up by env (Chen Bin)
