### ISSUE TITLE
per package ignores is maybe needed

### ISSUE THREAD

**Issue by thomasf** [redguardtoo/elpa-mirror#27]
as an example various tree sitter mode downloads loadable modules in when activated so when I tried to install the elpa mirror package on my macbook I made on my desktop I got linux amd64 libraries which it could not load so I had to delete them so they could be downloaded again.  For these specific modes I would like to exclude .so and .dynlib files so that the archive stays os independent.

**Comment by thomasf** [comment]
I guess an alternative solution is to lobby the package authors to include os/architecture in their binary file names but I counted at least 5 different package authors in my elpa/ directory that don't do that so it's probably good to have the possibility to filter at mirror creation time as well.

**Comment by redguardtoo** [comment]
Where the tree-sitter place those modules? Could you give me some example?

**Comment by thomasf** [comment]
This is the git diff of my elpa for the files I had to delete to stop get invalid module errors. I ran a couple of functions present in the two tree sitter packages to redownload the macos versions of the files here as well.

```
## master
R  ../tree-sitter-langs-20210113.1755/bin/agda.so -> ../tree-sitter-langs-20210113.1755/bin/agda.dylib
R  ../tree-sitter-langs-20210113.1755/bin/bash.so -> ../tree-sitter-langs-20210113.1755/bin/bash.dylib
R  ../tree-sitter-langs-20210113.1755/bin/c-sharp.so -> ../tree-sitter-langs-20210113.1755/bin/c-sharp.dylib
R  ../tree-sitter-langs-20210113.1755/bin/c.so -> ../tree-sitter-langs-20210113.1755/bin/c.dylib
R  ../tree-sitter-langs-20210113.1755/bin/cpp.so -> ../tree-sitter-langs-20210113.1755/bin/cpp.dylib
A  ../tree-sitter-langs-20210113.1755/bin/css.dylib
D  ../tree-sitter-langs-20210113.1755/bin/css.so
A  ../tree-sitter-langs-20210113.1755/bin/elm.dylib
A  ../tree-sitter-langs-20210113.1755/bin/fluent.dylib
D  ../tree-sitter-langs-20210113.1755/bin/fluent.so
A  ../tree-sitter-langs-20210113.1755/bin/go.dylib
D  ../tree-sitter-langs-20210113.1755/bin/go.so
A  ../tree-sitter-langs-20210113.1755/bin/html.dylib
D  ../tree-sitter-langs-20210113.1755/bin/html.so
R  ../tree-sitter-langs-20210113.1755/bin/java.so -> ../tree-sitter-langs-20210113.1755/bin/java.dylib
R  ../tree-sitter-langs-20210113.1755/bin/javascript.so -> ../tree-sitter-langs-20210113.1755/bin/javascript.dylib
A  ../tree-sitter-langs-20210113.1755/bin/jsdoc.dylib
D  ../tree-sitter-langs-20210113.1755/bin/jsdoc.so
A  ../tree-sitter-langs-20210113.1755/bin/json.dylib
D  ../tree-sitter-langs-20210113.1755/bin/json.so
R  ../tree-sitter-langs-20210113.1755/bin/julia.so -> ../tree-sitter-langs-20210113.1755/bin/julia.dylib
R  ../tree-sitter-langs-20210113.1755/bin/ocaml.so -> ../tree-sitter-langs-20210113.1755/bin/ocaml.dylib
R  ../tree-sitter-langs-20210113.1755/bin/php.so -> ../tree-sitter-langs-20210113.1755/bin/php.dylib
A  ../tree-sitter-langs-20210113.1755/bin/python.dylib
D  ../tree-sitter-langs-20210113.1755/bin/python.so
R  ../tree-sitter-langs-20210113.1755/bin/ruby.so -> ../tree-sitter-langs-20210113.1755/bin/ruby.dylib
R  ../tree-sitter-langs-20210113.1755/bin/rust.so -> ../tree-sitter-langs-20210113.1755/bin/rust.dylib
R  ../tree-sitter-langs-20210113.1755/bin/scala.so -> ../tree-sitter-langs-20210113.1755/bin/scala.dylib
A  ../tree-sitter-langs-20210113.1755/bin/swift.dylib
D  ../tree-sitter-langs-20210113.1755/bin/swift.so
R  ../tree-sitter-langs-20210113.1755/bin/tsx.so -> ../tree-sitter-langs-20210113.1755/bin/tsx.dylib
R  ../tree-sitter-langs-20210113.1755/bin/typescript.so -> ../tree-sitter-langs-20210113.1755/bin/typescript.dylib
 D tsc-dyn.so
?? tsc-dyn.dylib
```

**Comment by thomasf** [comment]
tree-sitter-langs-install-grammars installed all the modules for that package and I think just activating global-tree-sitter-mode fetched the tsc-package file.. 

I do not use these package directly, it looks like it's csharp-mode that pulls them in which I haven't used in the last two years so I don't even know if this is enough. I can test loading up a c sharp project tomorrow and see if I can test that it works.

**Comment by redguardtoo** [comment]
47f194c can exclude some files and directories inside package directory (Chen Bin)

**Comment by thomasf** [comment]
for future proofing it would probably be great if an ignore pattern also could be in the form of ("package-name" . "pattern") or something similar to target a specific package but that can be added later if needed.
