### ISSUE TITLE
Creating TAR Error

### ISSUE THREAD

**Issue by ericzzh** [redguardtoo/elpa-mirror#37]
Hi, 

Could you please help check this issue?
thanks.

* Detected tar variant: GNU
* Converted to full path: "/Users/zzh/" "ace-window-20200606.1259" -> "/Users/zzh/ace-window-20200606.1259"
* Running tar: "tar" ("cf" "/Users/zzh/ace-window-20200606.1259.tar" "--anchored" "--exclude=*.elc" "--exclude=*~" "--exclude=*.so" "--exclude=*.dylib" "--exclude=*.dll" "--exclude=*/bin" "--exclude=*/__pycache__" "--format=gnu" "--sort=name" "--owner=root:0" "--group=root:0" "--mtime=1970-01-01 00:00:00 UTC" "-C" "/Users/zzh/.emacs.d/elpa" "--" "ace-window-20200606.1259")
tar: Failed to set default locale
tar: Option --anchored is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
* Program tar exited with non-zero status 1, see the *elpa-mirror log* buffer for details

**Comment by ericzzh** [comment]
tar version
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6

elpa-mirror version:
‘elpa-mirror-20210304.1432/’ 

emacs version:
27.1(9.0)

**Comment by redguardtoo** [comment]
d645c44 better algorithm to detect bsdtar (Chen Bin)

**Comment by ericzzh** [comment]
thanks, but the issue hasn't been cleared.

on my machine, tar --version shows:
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6

but when run in Emacs, the result is
Result: (**"tar: Failed to set default locale"** "bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzm...")

**Comment by redguardtoo** [comment]
![image](https://user-images.githubusercontent.com/184553/112452723-06ec3700-8dab-11eb-883e-d52587fbd0b7.png)
Show me the full log.

Besides, double check `Mx eval-expression (elpamr--is-bsd-tar)` returns `t`.

**Comment by ericzzh** [comment]
* Detected tar variant: GNU
* Converted to full path: "/Users/zzh/myelpa/" "ace-window-20200606.1259" -> "/Users/zzh/myelpa/ace-window-20200606.1259"
* Running tar: "tar" ("cf" "/Users/zzh/myelpa/ace-window-20200606.1259.tar" "--anchored" "--exclude=*.elc" "--exclude=*~" "--exclude=*.so" "--exclude=*.dylib" "--exclude=*.dll" "--exclude=*/bin" "--exclude=*/__pycache__" "--format=gnu" "--sort=name" "--owner=root:0" "--group=root:0" "--mtime=1970-01-01 00:00:00 UTC" "-C" "/Users/zzh/.emacs.d/elpa" "--" "ace-window-20200606.1259")
tar: Failed to set default locale
tar: Option --anchored is not supported
Usage:
  List:    tar -tf <archive-filename>
  Extract: tar -xf <archive-filename>
  Create:  tar -cf <archive-filename> [filenames...]
  Help:    tar --help
* Program tar exited with non-zero status 1, see the *elpa-mirror log* buffer for details

---
M-x eval-expression (elpamr--is-bsd-tar)
return nil
---
I removed the ^ ahead of the regex, and it worked.
![image](https://user-images.githubusercontent.com/9389005/112456538-d4840f00-8d95-11eb-9c57-98b02bc77501.png)
 
the reason is the following message shows ahead of the version result in Emacs's run
"tar: Failed to set default locale" 

but didn't show in the terminal run.

**Comment by redguardtoo** [comment]
What's the output of `tar --version`?

**Comment by ericzzh** [comment]
> thanks, but the issue hasn't been cleared.
> 
> on my machine, tar --version shows:
> bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
> 
> but when run in Emacs, the result is
> Result: (**"tar: Failed to set default locale"** "bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzm...")

as the last comment
tar --version on my terminal shows
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6

but under the Emacs the additional message
tar: Failed to set default locale
shows before the normal result.
The message was concated as 
"tar: Failed to set default locale bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6"
which prevented the bsd tar regex check from passed.

**Comment by redguardtoo** [comment]
macOS? Have you tried to fix locale first? see https://blog.remibergsma.com/2012/07/10/setting-locales-correctly-on-mac-osx-terminal-application/

**Comment by ericzzh** [comment]
worked!
thanks very much!
closed.
