### ISSUE TITLE
tar: unrecognized option '--sort=name'

### ISSUE THREAD

**Issue by baolonglin** [redguardtoo/elpa-mirror#39]
Hi,

--sort was introduced in 1.28 according: https://www.gnu.org/software/tar/

The tar version on my SuSE 12 is 1.27.1
Do you have plan to support the old tar version?

Below is the full *elpa-mirror log*:
> * Detected tar variant: GNU
> * Converted to full path: "~/.elpa-mirror/" "ace-window-20200606.1259" -> "/home/baolong/.elpa-mirror/ace-window-20200606.1259"
> * Running tar: "tar" ("cf" "/home/baolong/.elpa-mirror/ace-window-20200606.1259.tar" "--anchored" "--exclude=*.elc" "--exclude=*~" "--exclude=*.so" "--exclude=*.dylib" "--exclude=*.dll" "--exclude=*/bin" "--exclude=*/__pycache__" "--format=gnu" "--sort=name" "--owner=root:0" "--group=root:0" "--mtime=1970-01-01 00:00:00 UTC" "-C" "/local/users/baolong/workspace/emacs.d/elpa" "--" "ace-window-20200606.1259")
> /bin/tar: unrecognized option '--sort=name'
> Try 'tar --help' or 'tar --usage' for more information.
> * Program tar exited with non-zero status 64, see the *elpa-mirror log* buffer for details

**Comment by redguardtoo** [comment]
63f8696 gnu tar 1.28 add --sort (Chen Bin)
