### ISSUE TITLE
Directory name format recognition problem

### ISSUE THREAD

**Issue by GreyZhang** [redguardtoo/elpa-mirror#40]
![image](https://user-images.githubusercontent.com/11857400/114414884-cd586000-9be1-11eb-8894-0b9bcd310731.png)

If the letter string is inserted into the number string behind the plug-in package, the tar file generation is unsuccessful.
exp:
evil-unimpaired-0.1pre0.20210412.213818 would not be packed as tar file, yet evil-unimpaired-20210412.213818 is ok.

**Comment by redguardtoo** [comment]
Yes, I think the regular expression failed to extract version number.

**Comment by redguardtoo** [comment]
ea868b5 package version might contain other characters (Chen Bin)

**Comment by GreyZhang** [comment]
The latest version wroks!

**Comment by redguardtoo** [comment]
you can run it as script in shell
