### ISSUE TITLE
Mirror not Showing up in Emacs under Archives

### ISSUE THREAD

**Issue by Justintime50** [redguardtoo/elpa-mirror#42]
I followed the instructions found in the README and built a mirror of my installed packages just fine; however, when adding the mirror to emacs, it's not pulling any of the packages in at all:

My archive: https://github.com/Justintime50/myelpa

What I added to `~/.emacs`: 
```lisp
(add-to-list 'package-archives '("myelpa" . "https://raw.githubusercontent.com/Justintime50/myelpa/main/"))
```

I've tried running `package-refresh-contents` and it says it pulls from raw.githubusercontent.com fine but none of the packages appear in `list-packages`. I'm running Emacs v27.2 on macOS. Does the README need to be updated or have I done something wrong?

**Comment by redguardtoo** [comment]
Can't reproduce the issue.
![image](https://user-images.githubusercontent.com/184553/142318802-65be88db-fa3e-4309-a33a-e267dac371aa.png)

**Comment by Justintime50** [comment]
I tried the `push` command suggested with no luck.

If I run `M-x describe-variable package-archives`, I get the following:

![Screen Shot 2021-11-17 at 8 24 01 PM](https://user-images.githubusercontent.com/39606064/142346160-048571de-fe7f-43c3-b38b-2628b3c5da53.png)

I removed all other items from my config thinking it was due to something else I had done but even with only specifying this package-archive and initializing emacs, it still won't show up.

**Comment by redguardtoo** [comment]
The installed packages overshadows the package of myelpa. Look like nothing is wrong.

**Comment by Justintime50** [comment]
Thank you very much @redguardtoo for the sanity check, you are indeed correct! After uninstalling the manually added packages, I found that they do indeed pop up in the list of installable packages from the mirror!

I also want to thank you for this package, it seriously saved me at work because of some dumb TLS issues with Melpa. Using this package I could make a mirror from my personal machine and drag it over to my work machine - big congrats on the great tool!

![Screen Shot 2021-11-17 at 11 54 40 PM](https://user-images.githubusercontent.com/39606064/142367216-fc149bd7-fb9c-477f-b409-74d79df27b89.png)
