### ISSUE TITLE
vagrant-tramp package produces a broken mirror.

### ISSUE THREAD

**Issue by Mihara** [redguardtoo/elpa-mirror#44]
Package [vagrant-tramp](https://melpa.org/#/vagrant-tramp) invariably results in a broken mirror archive, because it includes a file `bin/vagrant-tramp-ssh`.

Notably, it's required for the package to even load properly, so it not being there causes a lot of interesting issues.

I'm not sure how could one rewrite `elpamr-tar-command-exclude-patterns` to prevent this for specific packages...

**Comment by redguardtoo** [comment]
`(setq elpamr-tar-command-exclude-patterns '("*.elc")`

**Comment by Mihara** [comment]
That would be too broad from the other end, though. For example, `pdf-utils` builds a binary (`epdfinfo`) which also gets included in the tar. Along with all the object files, which would break on crossing from amd64 to arm, or between different distros.

I think some mechanism for setting this per-package is needed, such cases are rare, but they're tricky to debug.

**Comment by redguardtoo** [comment]
3e0fe0f can filter files&directories per package (Chen Bin)
