### ISSUE TITLE
windows7下执行elpamr-create-mirror-for-installed命令后，只是在myelpa文件生成了archive-contents文件，没有包的tar文件，

### ISSUE THREAD

**Issue by zhuljmike** [redguardtoo/elpa-mirror#46]
在windows7下使用elpa-mirror，
按照教程新建~/myelpa文件夹后，下载了tar并加入path，在emacs执行shell可以查询到tar，
c:\Users\mike\AppData\Local\emacs-29\bin>tar.exe --version
tar.exe --version
tar (GNU tar) 1.13

执行elpamr-create-mirror-for-installed命令后，只是在myelpa文件生成了archive-contents文件，没有包的tar文件
c:/Users/mike/AppData/Local/emacs-29/bin $ cd ~/myelpa/
~/myelpa $ pwd
c:/Users/mike/AppData/Roaming/myelpa
~/myelpa $ ls -la
total 17
drwxrwxrwx   1 mike           None     4096 2023-02-07 07:11 .
drwxrwxrwx   1 mike           None     4096 2023-02-07 05:54 ..
-rw-rw-rw-   1 mike           None     8986 2023-02-07 07:11 archive-contents

**Comment by redguardtoo** [comment]
a8ad2fb better algorithm to detect tar (Chen Bin)
