### ISSUE TITLE
Is there a way to update the mirror without updating the Emacs installation it's based on?

### ISSUE THREAD

**Issue by emacsomancer** [redguardtoo/elpa-mirror#48]
I was thinking it could be useful to have a way to keep the mirror up-to-date independently of the package installation of a particular instance of Emacs running on one's machine. (Basically thinking of this in the aftermath of [gnu.org, including elpa.gnu.org being down for a while](https://www.reddit.com/r/emacs/comments/121f486/savannahgnuorg_dns_problems/).

**Comment by redguardtoo** [comment]
Run `env HOME=/path/to/diremacs -Q  -l "~/.emacs.d/early-init.el" -l "~/.emacs.d/init.el"`
