### ISSUE TITLE
 [feature request] support emacs official package 'pacakge-vc.el'

### ISSUE THREAD

**Issue by ISouthRain** [redguardtoo/elpa-mirror#50]
你好, emacs 30 支持 package-vc.el 了, 希望对次支持  
package-vc.el 支持可以从 git repo 安装包  
package-vc.el 下载安装的包会在 .emacs.d/elpa/  文件夹下, 与 package.el 包路径相同  
例如:   
使用 package-vc.el  安装了一个包命为 test-package, 那么包含 .emacs.d/elpa/test-package/*.el   
执行 elpamr-create-mirror-for-installed 后, 假如: .emacs.d/elpa-local/ 为我备份路径
那么 .emacs.d/elpa-local/test-package.tar 里面的内容为空, 没有任何文件  
package.el 下载的包备份成功

**Comment by redguardtoo** [comment]
如果默认目录在elpa下,应该不需要额外工作就可以用的吧.

**Comment by ISouthRain** [comment]
> 如果默认目录在elpa下,应该不需要额外工作就可以用的吧.

不能, 虽然 elpamr-create-mirror-for-installed 已经对 test-package 包 压缩成了 test-package.tar ,  但是这个文件的内容为空

**Comment by redguardtoo** [comment]
package-vc的网站?

**Comment by ISouthRain** [comment]
> package-vc的网站?

https://github.com/emacs-mirror/emacs/blob/master/lisp/emacs-lisp/package-vc.el

**Comment by redguardtoo** [comment]
98ed08e support package-vc-install (package froms git repo) in emacs 29 (Chen Bin)

Could you help me on some regression test?

**Comment by ISouthRain** [comment]
> [98ed08e](https://github.com/redguardtoo/elpa-mirror/commit/98ed08e8bc55548326481204bc80267bd2eb4a58) support package-vc-install (package froms git repo) in emacs 29 (Chen Bin)
> 
> Could you help me on some regression test?

它工作良好, 至少我测试它没有问题
最后, 谢谢你的工作!!
